stateDiagram
    [*] --> SinHistoria
    SinHistoria --> ConHistoria: CrearHistoriaClinica
    ConHistoria --> ConHistoria: ActualizarHistoriaClinica
    ConHistoria --> SinHistoria: BorrarHistoriaClinica