stateDiagram
    [*] --> SinMedicamento
    SinMedicamento --> ConMedicamento: CrearMedicamento
    ConMedicamento --> ConMedicamento: ActualizarMedicamento
    ConMedicamento --> SinMedicamento: BorrarMedicamento